"""Add movie table and movie_genre

Revision ID: d11d5359e4ca
Revises: 
Create Date: 2020-09-27 23:20:58.300881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11d5359e4ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ninety_nine_popularity', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('director', sa.String(length=100), nullable=False),
    sa.Column('imdb_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'director', name='move_name_director_name')
    )
    op.create_index(op.f('ix_movie_director'), 'movie', ['director'], unique=False)
    op.create_index(op.f('ix_movie_imdb_score'), 'movie', ['imdb_score'], unique=False)
    op.create_index(op.f('ix_movie_name'), 'movie', ['name'], unique=False)
    op.create_index(op.f('ix_movie_ninety_nine_popularity'), 'movie', ['ninety_nine_popularity'], unique=False)
    op.create_table('movie_genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_genre_name'), 'movie_genre', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_genre_name'), table_name='movie_genre')
    op.drop_table('movie_genre')
    op.drop_index(op.f('ix_movie_ninety_nine_popularity'), table_name='movie')
    op.drop_index(op.f('ix_movie_name'), table_name='movie')
    op.drop_index(op.f('ix_movie_imdb_score'), table_name='movie')
    op.drop_index(op.f('ix_movie_director'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
